### ISSUE TITLE
XML Fehler beim Auflisten des Content

### ISSUE THREAD

**Issue by joluxer** [mmolch/dlna-downloader#3]
Hallo, ich bin auch sehr interessiert an dem Programm, sieht vielversprechend aus.

Wenn ich es starte, kommt im Terminal folgender Fehler-Log:
```
INFO:DlnaClientDevice:Initializing...
INFO:DlnaClientDevice:Found DIGA im Wohnzimmer
ERROR:DlnaClientDevice:'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
INFO:DlnaClientDevice:Initializing...
INFO:DlnaClientDevice:Found DIGA im Wohnzimmer
ERROR:DlnaClientDevice:'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```
Das Gerät "DIGA im Wohnzimmer" wird aber nicht im UI angezeigt.

Mit dem `vlc` kann ich die Titel im Gerät auflisten und auch abspielen. Da ich sie einfach nur lokal kopieren möchte, kommt der Downloader wieder ins Spiel. 

Wenn's hilft, kann ich den Wireshark-Mitschnitt einer erfolgreichen VLC-Session beistellen.

Viele Grüße, Jo

**Comment by mmolch** [comment]
Fixed in version 1.1
